apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: donetick
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`donetick.morawskim.pl`)
      services:
        - kind: Service
          name: donetick
          port: 80
      middlewares:
      #   - name: openid-auth
        - name: add-x-forwarded-proto
  tls:
    certResolver: myresolver
