---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: donetick
  namespace: prod
spec:
  encryptedData:
    DT_JWT_SECRET: AgC6cxRVr/oDgAmmIyj4t+NpgtZ7lUFWV20ipMfAjcpdt11+1q5MMI+7lLbGD52vzmXhIKuyHlXpJ700dKlSbrvhc3smJr8u997Fe77t7uWBY32ucUkwNqYuRLK0qYTM1xPrOB6Gu+2Dtz4Dufn8AMQLWsoqoqA0TqOJjb8lW7yRtZvbA1DdmCHael3HryCLgi8GJu6328g/4VAC6oCjKpirUEiwmFtEK3U5FpMhXnCV2DeAbUXBHnCDaEty88FoyFqSphZLi8yRtytZZJFgHnvXY/ax5f81N/oc6HW35TaPcxTli3GfpJfoqJq324BwUXeBwXYUrrJq9dbi76yOvvi6c8i5HjN64l4b5jpY4hXpJmpbD8GwGsjQNSuLeovxqwrzGlwcVnTxeSswO02A/YQiGY1B+RHBXAxzNIsikIGwPEmWpTsSAI4zlHweDTmmiFzRfsPMtgB8D6rq4JUgmDCVI+96pFctxPu1Y+N8OlE0K2fMt/zsAHoyJbL6jXuQPO99N0Usc8ryqMVl8EbnvZr0ltcfRASfaYdzp6GzvIM1RwXEn3glQZYmQ6MZRqWUkfq8rflxCrhGfBtTm797JU51vhiRXIYuXQYWJZOuGDidO8LTclKaeJvihOpDvmsNFuBMxrqfbVR2CsXJKKoBqzZumxI9wYB24E2KJbpTBi5xF545XjFE6fU7ejtdPiwuWjXfWdhj8AXRZ+3eY2y5SRJ9ncCuswCK2ltcXyG3odJ5/iPom2rXR/Fwb/1RxT41tDmZpw==
  template:
    metadata:
      creationTimestamp: null
      name: donetick
      namespace: prod