# DNS servers that pi-hole will use
DNS1: 9.9.9.9
DNS2: 1.1.1.1

persistentVolumeClaim:
  enabled: true

admin:
  # use the secret we just created
  existingSecret: "pihole-admin"

serviceDns:
  # combine the TCP and UDP services
  mixedService: true

# we won't need that
serviceDhcp:
  enabled: false

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 9.9.9.9
