apiVersion: v1
data:
  config.yml: |
    github_releases:
      morawskim/faker-cli: 2.0.0
      mvisonneau/gitlab-ci-pipelines-exporter: 0.5.6
      tellerops/teller: 2.0.7
      Luzifer/ots: 1.11.0
      traefik/traefik-helm-chart: 30.0.2
      fluent/helm-charts: 0.47.5
      knative/operator: 1.20.1
      google/cadvisor: 0.55.1
      open-webui/open-webui: 0.7.2
    docker_images:
      library/php: 8.2.0
      morawskim/htrace.sh: 1.1.7
      library/redis: 7.0.0
      dgtlmoon/changedetection.io: 0.48.05
    github_tags:
      stasiu20/ssorder: 2.21.0
      morawskim/faker-images: 0.8.0
      trimstray/htrace.sh: 1.1.7
    quary_images:
      jupyter/base-notebook: notebook-7.3.1
kind: ConfigMap
metadata:
  name: up-to-date-exporter
