namespace: cadvisor

resources:
- ./namespace.yaml
- ../../base/cadvisor
patches:
- path: cadvisor-patch.yaml
images:
  - name: ghcr.io/google/cadvisor
    newTag: "0.55.1"

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
