apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freshrss
  name: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  strategy: {}
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data
        - name: freshrss-extensions
          persistentVolumeClaim:
            claimName: freshrss-extensions
      containers:
      - image: freshrss/freshrss:1.28.0
        name: freshrss
        env:
        - name: TZ
          value: Europe/Warsaw
        - name: CRON_MIN
          value: "3,33"
        volumeMounts:
          - name: freshrss-data
            mountPath: /var/www/FreshRSS/data
          - name: freshrss-extensions
            mountPath: /var/www/FreshRSS/extensions
        resources: {}
      - image: ghcr.io/flaresolverr/flaresolverr:latest
        name: flaresolverr
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freshrss-mysql
spec:
  selector:
    matchLabels:
      app: freshrss-mysql
  serviceName: "freshrss-mysql"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: freshrss-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.4
        args:
          - --mysql-native-password=ON
          - --innodb-buffer-pool-size=32M
          - --innodb-buffer-pool-chunk-size=32M
          - --key-buffer-size=1M
          - --performance-schema=OFF
          - --max-connections=5
          - --binlog-expire-logs-seconds=43200
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: 320M
          limits:
            memory: 320M
        env:
        - name: TZ
          value: Europe/Warsaw
        envFrom:
        - secretRef:
            name: freshrss-mysql
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysql -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
          initialDelaySeconds: 10
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "microk8s-hostpath"
      resources:
        requests:
          storage: 1Gi
