apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: freshrss
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`freshrss.10.0.2.15.nip.io`)
      services:
        - kind: Service
          name: freshrss
          port: 80
      middlewares:
        - name: add-x-forwarded-proto
  tls:
    certResolver: myresolver
