apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-extensions
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 100Mi

