apiVersion: v1
kind: Service
metadata:
  name: open-webui-external
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: open-webui-external
  labels:
    kubernetes.io/service-name: open-webui-external
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 3000
endpoints:
  - addresses:
      - "192.168.33.201"
    conditions:
      ready: true
