---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgCG5ECwggAdcY9ZWsydUEcDDoec6BDLHs7E+f0+ZmtSM9UUsc9UnU0FOsSjMWYzq5jmmuO/nvR3BZl5XeKG7jjMtI9DdU8U1iRz0PVOLXBGym6Rufhkh1Jd1VD74sn1Nhr5xLkZlUCbprcrql3iy+WHjfgC0XSFlnLw5LubjzvyPCJrJblkpwesadXxNK6QUnKdgxIEfpljsJEY5VDN0wT2G2oPDYtG04azsCrxtd/7A7yQlApb0NG7Es62Dl25m3k8oWdBhAv5scHCLd/cTe6la1t17PCiIDgLE85+UKer/G1r1InzMHkbLJiLb+QrYcZg4UdUnhilis0NyoNKFieHOnWSGhJkdVel0ClWsjNwBLX2AwBBadT5AM/MI1HMjm04MyP51IJ141kw18bXMoLjYnQr28YiYCZFrc2ON2GGZdbffgzzu6aOoVmQj0nBGqPOrep1ZgkeTDXRJwAlySMRunHOgW3O51OyMJrqLfCfCFkxnXoa9hSjFfZPnmSjOdaxvYEBq1Y89L5a7mEysNkhmVqV+Fe4wGuRF9agZgzppmHeXPhQGe0KPLObukYvRXSKrPXu0oZsPzA6q2VOtCds000sRtHxVi1tcta8pCwuSg+1IyZ9xLiJ8QktzrHZFsLjYJlFt7BppIKegd7Mg7jo/VI0ToaMd8OXja60F3Qt0uq0XOOlZfWcVI3otigzBS6S3WHozaLAwJyeTmxNoZjGrWXgUg==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-admin
      namespace: pihole
    type: Opaque