apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: knative
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`^.+\.knative-serving\.morawskim\.pl$`)
      kind: Rule
      services:
        - name: kourier-internal
          namespace: knative-serving
          port: 80
