apiVersion: v1
kind: ConfigMap
metadata:
  name: clair-config
data:
  config.yaml: |
    introspection_addr: ":8089"
    http_listen_addr: ":6060"
    log_level: debug

    # updaters:
    #   sets:
    #     - ubuntu
    #     - alpine
    #     - redhat
    #     - debian


    indexer:
        connstring: "postgres://postgres:password@clair-postgres:5432/clair?sslmode=disable"
        migrations: true
    matcher:
        connstring: "postgres://postgres:password@clair-postgres:5432/clair?sslmode=disable"
        indexer_addr: http://localhost:6060/
        migrations: true
    notifier:
        connstring: "postgres://postgres:password@clair-postgres:5432/clair?sslmode=disable"
        migrations: true
        indexer_addr: http://localhost:6060/
        matcher_addr: http://localhost:6060/
