apiVersion: apps/v1
kind: Deployment
metadata:
  name: clair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clair
  template:
    metadata:
      labels:
        app: clair
    spec:
      containers:
      - name: clair
        image: quay.io/projectquay/clair:4.7.4
        # command: ["/clair"]
        # args: ["-conf", "/config/config.yaml"]
        ports:
        - containerPort: 6060
        volumeMounts:
        - name: config
          mountPath: /config
        - name: config-base
          mountPath: /config/config.yaml.d
        - name: config-extra
          mountPath: /config/config.yaml.d/10-db-connstring.yaml
          subPath: 10-db-connstring.yaml
        env:
          - name: CLAIR_MODE
            value: combo
          - name: GOMEMLIMIT
            value: "850MiB"
        resources:
          requests:
            cpu: 50m
            memory: 50M
          limits:
            cpu: 1000m
            memory: 1524M
      volumes:
      -  name: config-base
         emptyDir: {}
      - name: config
        configMap:
          name: clair-config
      - name: config-extra
        secret:
          secretName: clair
          items:
            - key: 10-db-connstring.yaml
              path: 10-db-connstring.yaml
