apiVersion: apps/v1
kind: Deployment
metadata:
  name: clair-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clair-postgres
  template:
    metadata:
      labels:
        app: clair-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clair
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: clair
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
        args:
          - -c
          - shared_buffers=100MB
          - -c
          - effective_cache_size=350MB
        resources:
          requests:
            cpu: 50m
            memory: 50M
          limits:
            cpu: 400m
            memory: 500M
      volumes:
      - name: pg-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: clair-postgres
spec:
  ports:
  - port: 5432
  selector:
    app: clair-postgres
